kind: Deployment
apiVersion: apps/v1
metadata:
    name: mydeployments
spec:
replicas: 1
selector:
  matchLabels:
    app: springboot-k8s
  template:
    metadata:
      labels:
         app: springboot-k8s
    spec:
    containers:
     - name: springboot-k8s
       image: anuragjoshi01/kubernetes
       imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 8000

---
kind: Service
apiVersion: v1
metadata: 
    name: springboot-k8s-svc
spec:
    type: NodePort
    selector:
       app: springboot-k8s
    ports:
    - nodePort: 30163
      port: 8000
      targetPort: 8000

